---
version: '3.7'
services:
  api:
    image: stonk/api:${env}
    build:
      context: api
    container_name: stonk-be-api-${env}
    expose:
      - 80
    ports:
      - "8080:80"
    networks:
      default:
        aliases:
          - api.amanze.local
      proxy:
        aliases:
          - api.amanze.local
    restart: always
    depends_on:
      - database
    healthcheck:
      test: node healthcheck.js || exit 1
      interval: 20s
      timeout: 3s
      retries: 5
      start_period: 15s
    environment:
      # VIRTUAL_PORT: 80
      HOST: 0.0.0.0
      PORT: 80
      DB_CONNECTION: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: platform-api
      DB_DATABASE: platform-api
      VIRTUAL_HOST: api.amanze.local
      DB_PASSWORD: database_password
      APP_KEY: random_128_bit_string

  database:
    image: postgres:11.6-alpine
    container_name: stonk-be-database-${env}
    stop_grace_period: 3s
    restart: always
    ports:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U platform-api
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: platform-api
      POSTGRES_USER: platform-api      
      POSTGRES_PASSWORD: database_password

networks:
  proxy:
    external:
      name: nginx_proxy

volumes:
  database:
